sudo: false
matrix:
  include:
    - language: objective-c
      before_script:
        - cd ios
      script:
        - ./build.sh
    - language: node_js
      node_js:
        - "6"
        - "8"
        - "node"
      cache:
        directories:
          - "node_modules"
      before_script:
        - cd nodejs
        - npm install
      script:
        - npm run lint
        - npm test
